
:version:
  :name: tag_config
  :current: 0.1
  :authors: ["Chad Thatcher", "Sandra Tuppen", "Laurent Pugin", "Rodolfo Zitellini"]


# People auth data

:model: catalogue
:tags:
  "000":
    :master: ""
    :indicator: ""
    :occurrences: "1"
    :fields:
    - - ""
      - :no_browse: true
  "001":
    :master: ""
    :indicator: ""
    :occurrences: "1"
    :zero_padding: "14"
    :fields:
    - - ""
      - :no_browse: true
  "003":
    :master: ""
    :indicator: ""
    :occurrences: "1"
    :fields:
    - - ""
      - :no_browse: true
  "005":
    :master: ""
    :indicator: ""
    :occurrences: "1"
    :fields:
    - - ""
      - :no_browse: true
  "008":
    :master: ""
    :indicator: ""
    :occurrences: "1"
    :fields:
    - - ""
      - :no_browse: true
  "100":
    :master: a
    :indicator: "1#"
    :occurrences: "?"
    :fields:
    - - a
      - :occurrences: "?"
    - - "0"
      - :occurrences: "?"
        :browse_inline: true
  "210":
    :master: a
    :indicator: "1#"
    :occurrences: "?"
    :fields:
    - - a
      - :occurrences: "?"
  "240":
    :master: a
    :indicator: "1#"
    :occurrences: "?"
    :fields:
    - - a
      - :occurrences: "?"
  "260":
    :master: a
    :indicator: "1#"
    :occurrences: "*"
    :fields:
    - - a
      - :occurrences: "?"
    - - c
      - :occurrences: "?"
  "700":
    :master: a
    :indicator: "##"
    :occurrences: "*"
    :fields:
    - - a
      - :occurrences: "?"
    - - "0"
      - :occurrences: "?"
    - - "4"
      - :occurrences: "?"
  "760":
    :master: g
    :indicator: "##"
    :occurrences: "*"
    :fields:
    - - g
      - :occurrences: "?"
    - - t
      - :occurrences: "?"
