
:version:
  :name: tag_config
  :current: 0.1
  :authors: ["Chad Thatcher", "Sandra Tuppen", "Laurent Pugin", "Rodolfo Zitellini"]


# People auth data

:model: institution
:tags:
  "000":
    :master: ""
    :indicator: ""
    :occurrences: "1"
    :fields:
    - - ""
      - :no_browse: true
  "001":
    :master: ""
    :indicator: ""
    :occurrences: "1"
    :zero_padding: "14"
    :fields:
    - - ""
      - :no_browse: true
  "003":
    :master: ""
    :indicator: ""
    :occurrences: "1"
    :fields:
    - - ""
      - :no_browse: true
  "005":
    :master: ""
    :indicator: ""
    :occurrences: "1"
    :fields:
    - - ""
      - :no_browse: true
  "008":
    :master: ""
    :indicator: ""
    :occurrences: "1"
    :fields:
    - - ""
      - :no_browse: true
  "043":
    :master: c
    :indicator: "##"
    :occurrences: "*"
    :fields:
    - - c
      - :occurrences: "*"
  "110":
    :master: a
    :indicator: "1#"
    :occurrences: "?"
    :fields:
    - - a
      - :occurrences: "?"
    - - c
      - :occurrences: "?"
    - - g
      - :occurrences: "?"
  "410":
    :master: a
    :indicator: "1#"
    :occurrences: "*"
    :fields:
    - - a
      - :occurrences: "?"
  "622":
    :master: e
    :indicator: "##"
    :occurrences: "*"
    :fields:
    - - e
      - :occurrences: "?"
    - - u
      - :occurrences: "?"
        :validation: "^http*"
  "680":
    :master: i
    :indicator: "1#"
    :occurrences: "*"
    :fields:
    - - i
      - :occurrences: "?"
