--- !map:Settings 
"000": 
  tag: tag_no_subfield
  tag_params: 
    editor_only: true
  tag_header: none
"001": 
  tag: tag_no_subfield
  tag_params: 
    read_only: true
  tag_header: none
"003": 
  tag: tag_no_subfield
  tag_params: 
    read_only: true
  tag_header: none
"005": 
  tag: tag_no_subfield
  tag_params: 
    read_only: true
  tag_header: none
008: 
  tag: tag_no_subfield
  tag_params: 
    maskedinput: 
      definitions: "['~']='[|0-9]'"
      mask: 999999a~~~~~~~~||||||||||||||||||||aaa|d
  tag_header: none
"100": 
  layout: 
    fields: 
    - - a
"210": 
  layout: 
    fields: 
    - - a
"240": 
  layout: 
    fields: 
    - - a
"260": 
  layout: 
    fields: 
    - - a
    - - c
"700": 
  layout: 
    fields: 
    - - a
"760": 
  layout: 
    fields: 
    - - g
    - - t

