--- !map:Settings 
group_order: 
- control
- codes
- main
- title
- edition
- description
- notes
- subject
- added_entry
- linking
- holding
groups: 
  control: 
    all_tags: 
    - "000"
    - "001"
    - "003"
    - "007"
  added_entry: 
    all_tags: 
    - "700"
    - "710"
    - "730"
    - "740"
  added_series: 
    all_tags: []

  title: 
    all_tags: 
    - "240"
    - "245"
    - "246"
  notes: 
    all_tags: 
    - "500"
    - "505"
    - "506"
    - "508"
    - "510"
    - "511"
    - "518"
    - "520"
    - "525"
    - "533"
    - "541"
    - "545"
    - "546"
    - "555"
    - "561"
    - "563"
    - "580"
    - "590"
    - "591"
    - "592"
    - "593"
    - "594"
    - "595"
    - "596"
    - "597"
    - "598"
    - "599"
  series: 
    all_tags: []

  holding: 
    all_tags: 
    - "852"
    - "856"
  subject: 
    all_tags: 
    - "600"
    - "650"
    - "651"
    - "653"
    - "657"
    - "690"
    - "691"
  main: 
    all_tags: 
    - "100"
    - "110"
    - "130"
  description: 
    all_tags: 
    - "300"
    - "340"
  codes: 
    all_tags: 
    - 028
    - "031"
    - "033"
    - "035"
    - "040"
    - "041"
  linking: 
    all_tags: 
    - "772"
    - "773"
    - "787"
    - "789"
  edition: 
    all_tags: 
    - "254"
    - "260"
    - "270"
