--- !map:Settings 
group_order: 
- library
- provenance
- linkage
- diplomatic_title
- physical_description
- material_description
- content
- bibliographical_reference
- added_entries
- date
- administration
