--- !map:Settings 
"000": 
  tag: tag_no_subfield
  tag_params: 
    editor_only: true
  tag_header: none
"001": 
  tag: tag_no_subfield
  tag_params: 
    read_only: true
  tag_header: none
"003": 
  tag: tag_no_subfield
  tag_params: 
    read_only: true
  tag_header: none
"005": 
  tag: tag_no_subfield
  tag_params: 
    read_only: true
  tag_header: none
008: 
  tag: tag_no_subfield
  tag_params: 
    maskedinput: 
      definitions: "['~']='[|0-9]'"
      mask: 999999a~~~~~~~~||||||||||||||||||||aaa|d
  tag_header: none
"035": 
    layout: 
      fields: 
      - - a
"039": 
  layout: 
    fields: 
    - - a
"040": 
  layout: 
    fields: 
    - - a
    - - c
    - - d
    - - b
"043": 
  layout: 
    fields: 
    - - a
    - - b
    - - c
"100": 
  layout: 
    fields: 
    - - a
    - - d
"400": 
  layout: 
    fields: 
    - - a
    - - d
"509": 
  layout: 
    fields: 
    - - a
"549": 
  layout: 
    fields: 
    - - a
"559": 
  layout: 
    fields: 
    - - a
"569": 
  layout: 
    fields: 
    - - a
"670": 
  layout: 
    fields: 
    - - a
"678": 
  layout: 
    fields: 
    - - a
    - - b
    - - u
"680": 
  layout: 
    fields: 
    - - i
"684": 
  layout: 
    fields: 
    - - a
    - - j