--- 
###
- :id: DefaultCH
  :name: Default (CH)
  :model: source
  :labels: 
  - BasicLabels
  :rules: 
  - BasicCataloguingRules
  :options: 
  - BasicFormOptions
  :layout: 
  - LayoutDefaultCH
  :filter: 
    default: true
###
- :id: ConvolutumCH
  :name: Convolutum (CH)
  :model: source
  :labels: 
  - BasicLabels
  :rules: 
  - BasicCataloguingRules
  :options: 
  - BasicFormOptions
  :layout: 
  - LayoutPartAdministrationCH
  - LayoutPartLibraryConvolutumCH
  - LayoutPartProvenanceCH
  - LayoutPartAddedEntriesCH
  - LayoutPartDiplomaticTitleCH
  - LayoutPartBibRefAttributedCH
  - LayoutPartLinkageConvolutumCH
  - LayoutPartDateCH
  - LayoutConvolutumCH
  :filter:
    leader: !ruby/regexp /......pd.............../
###
- :id: CollectionCH
  :name: Collection (CH)
  :model: source
  :labels: 
  - BasicLabels
  :rules: 
  - BasicCataloguingRules
  :options: 
  - BasicFormOptions
  :layout: 
  - LayoutPartAdministrationCH
  - LayoutPartLibraryCollectionCH
  - LayoutPartProvenanceCH
  - LayoutPartDiplomaticTitleCH
  - LayoutPartPhysicalDescriptionMusicCH
  - LayoutPartContentCollectionCH
  - LayoutPartAddedEntriesCH
  - LayoutPartBibRefAttributedCH
  - LayoutPartLinkageCollectionCH
  - LayoutPartDateCH
  - LayoutCollectionCH
  :filter:
    leader: !ruby/regexp /......[dc]c.............../
    tag: "110"
###
- :id: LibrettoAnonymousCH
  :name: Libretto Anonymous (CH)
  :model: source
  :labels: 
  - BasicLabels
  :rules: 
  - BasicCataloguingRules
  :options: 
  - BasicFormOptions
  :layout: 
  - LayoutPartAdministrationCH
  - LayoutPartLibraryCH
  - LayoutPartProvenanceCH
  - LayoutPartDiplomaticTitleCH
  - LayoutPartPhysicalDescriptionLibrettoCH
  - LayoutPartContentLibrettoAnonymousCH
  - LayoutPartAddedEntriesCH
  - LayoutPartDateCH
  - LayoutPartPerformanceCH
  - LayoutPartBibRefLibrettoAnonymousCH
  - LayoutLibrettoAnonymousCH
  :filter:
    leader: !ruby/regexp /......[at]m.............../
    tag: "130"
###
- :id: LibrettoAttributedCH
  :name: Libretto Attributed (CH)
  :model: source
  :labels: 
  - BasicLabels
  :rules: 
  - BasicCataloguingRules
  :options: 
  - BasicFormOptions
  :layout: 
  - LayoutPartAdministrationCH
  - LayoutPartLibraryCH
  - LayoutPartProvenanceCH
  - LayoutPartDiplomaticTitleCH
  - LayoutPartPhysicalDescriptionLibrettoCH
  - LayoutPartContentLibrettoAttributedCH
  - LayoutPartAddedEntriesCH
  - LayoutPartDateCH
  - LayoutPartPerformanceCH
  - LayoutPartBibRefLibrettoAttributedCH
  - LayoutLibrettoAttributedCH
  :filter:
    leader: !ruby/regexp /......[at]m.............../
    tag: "100"
###
- :id: AnonymousWorkCH
  :name: Anonymous Work (CH)
  :model: source
  :labels: 
  - BasicLabels
  :rules: 
  - BasicCataloguingRules
  :options: 
  - BasicFormOptions
  :layout: 
  - LayoutPartAdministrationCH
  - LayoutPartLibraryCH
  - LayoutPartProvenanceCH
  - LayoutPartDiplomaticTitleCH
  - LayoutPartPhysicalDescriptionMusicCH
  - LayoutPartContentAnonymousWorkCH
  - LayoutPartIncipitCH
  - LayoutPartAddedEntriesCH
  - LayoutPartDateCH
  - LayoutPartPerformanceCH
  - LayoutPartBibRefAnonymousCH
  - LayoutPartLinkageWorkCH
  - LayoutAnonymousWorkCH
  :filter:
    leader: !ruby/regexp /......[dc]m.............../
    tag: "130"
###
- :id: AnonymousWorkinCollectionCH
  :name: Anonymous Work in Collection (CH)
  :model: source
  :labels: 
  - BasicLabels
  :rules: 
  - BasicCataloguingRules
  :options: 
  - BasicFormOptions
  :layout: 
  - LayoutPartAdministrationCH
  - LayoutPartLibraryCH
  - LayoutPartProvenanceCH
  - LayoutPartDiplomaticTitleCH
  - LayoutPartPhysicalDescriptionMusicCH
  - LayoutPartContentAnonymousWorkCH
  - LayoutPartIncipitCH
  - LayoutPartAddedEntriesCH
  - LayoutPartDateCH
  - LayoutPartPerformanceCH
  - LayoutPartBibRefAnonymousCH
  - LayoutPartLinkageWorkCollectionCH
  - LayoutAnonymousWorkCollectionCH
  :filter:
    leader: !ruby/regexp /......[dc]d.............../
    tag: "130"
###
- :id: AttributedWorkCH
  :name: Attributed Work (CH)
  :model: source
  :labels: 
  - BasicLabels
  :rules: 
  - BasicCataloguingRules
  :options: 
  - BasicFormOptions
  :layout: 
  - LayoutPartAdministrationCH
  - LayoutPartLibraryCH
  - LayoutPartProvenanceCH
  - LayoutPartDiplomaticTitleCH
  - LayoutPartPhysicalDescriptionMusicCH
  - LayoutPartContentAttributedWorkCH
  - LayoutPartIncipitCH
  - LayoutPartAddedEntriesCH
  - LayoutPartDateCH
  - LayoutPartPerformanceCH
  - LayoutPartBibRefAttributedCH
  - LayoutPartLinkageWorkCH
  - LayoutAttributedWorkCH
  :filter:
    leader: !ruby/regexp /......[dc]m.............../
    tag: "100"
###
- :id: AttributedWorkinCollectionCH
  :name: Attributed Work in Collection (CH)
  :model: source
  :labels: 
  - BasicLabels
  :rules: 
  - BasicCataloguingRules
  :options: 
  - BasicFormOptions
  :layout: 
  - LayoutPartAdministrationCH
  - LayoutPartLibraryCH
  - LayoutPartProvenanceCH
  - LayoutPartDiplomaticTitleCH
  - LayoutPartPhysicalDescriptionMusicCH
  - LayoutPartContentAttributedWorkCH
  - LayoutPartIncipitCH
  - LayoutPartAddedEntriesCH
  - LayoutPartDateCH
  - LayoutPartPerformanceCH
  - LayoutPartBibRefAttributedCH
  - LayoutPartLinkageWorkCollectionCH
  - LayoutAttributedWorkCollectionCH
  :filter:
    leader: !ruby/regexp /......[dc]d.............../
    tag: "100"
###
- :id: TheoreticaAnonymousCH
  :name: Theoretica Anonymous (CH)
  :model: source
  :labels: 
  - BasicLabels
  :rules: 
  - BasicCataloguingRules
  :options: 
  - BasicFormOptions
  :layout: 
  - LayoutPartAdministrationCH
  - LayoutPartLibraryCH
  - LayoutPartProvenanceCH
  - LayoutPartDiplomaticTitleCH
  - LayoutPartPhysicalDescriptionTheoreticaCH
  - LayoutPartContentTheoreticaAnonymousCH
  - LayoutPartIncipitCH
  - LayoutPartAddedEntriesCH
  - LayoutPartBibRefTheoreticaCH
  - LayoutTheoreticaAnonymousCH
  :filter:
    leader: !ruby/regexp /......pm.............../
    tag: "130"
###
- :id: TheoreticaAttributedCH
  :name: Theoretica Attributed (CH)
  :model: source
  :labels: 
  - BasicLabels
  :rules: 
  - BasicCataloguingRules
  :options: 
  - BasicFormOptions
  :layout: 
  - LayoutPartAdministrationCH
  - LayoutPartLibraryCH
  - LayoutPartProvenanceCH
  - LayoutPartDiplomaticTitleCH
  - LayoutPartPhysicalDescriptionTheoreticaCH
  - LayoutPartContentTheoreticaAttributedCH
  - LayoutPartIncipitCH
  - LayoutPartAddedEntriesCH
  - LayoutPartBibRefTheoreticaCH
  - LayoutTheoreticaAttributedCH
  :filter:
    leader: !ruby/regexp /......pm.............../
    tag: "100"
- :id: ShowCH
  :name: Show (CH)
  :model: source
  :labels: 
  - BasicLabels
  :rules: 
  - BasicCataloguingRules
  :options: 
  - BasicFormOptions
  :layout: 
  - LayoutShowCH
  :filter:
    show_all: false
    show: true

# Configuration for person
- :id: DefaultPerson
  :name: Default Person
  :model: person
  :labels: 
  - PersonBasicLabels
  :rules: 
  - BasicCataloguingRules
  :options: 
  - PersonBasicFormOptions
  :layout: 
  - PersonLayoutDefault
  :filter: 
    default: true
- :id: ShowPerson
  :name: Show Person
  :model: person
  :labels: 
  - PersonBasicLabels
  :rules: 
  - BasicCataloguingRules
  :options: 
  - PersonBasicFormOptions
  :layout: 
  - PersonLayoutShow
  :filter:
    show_all: false
    show: true

- :id: DefaultInstitution
  :name: Institution
  :model: institution
  :labels: 
  - InstitutionBasicLabels
  :rules: 
  - BasicCataloguingRules
  :options: 
  - InstitutionBasicFormOptions
  :layout: 
  - InstitutionLayoutDefault
  :filter:
    default: true 
- :id: ShowInstitution
  :name: Institution
  :model: institution
  :labels: 
  - InstitutionBasicLabels
  :rules: 
  - BasicCataloguingRules
  :options: 
  - InstitutionBasicFormOptions
  :layout: 
  - InstitutionLayoutShow
  :filter:
    show_all: false
    show: true

- :id: DefaultCatalogue
  :name: Catalogue
  :model: catalogue
  :labels: 
  - CatalogueBasicLabels
  :rules: 
  - BasicCataloguingRules
  :options: 
  - CatalogueBasicFormOptions
  :layout: 
  - CatalogueLayoutDefault
  :filter:
    default: true 
- :id: ShowCatalogue
  :name: Catalogue
  :model: catalogue
  :labels: 
  - CatalogueBasicLabels
  :rules: 
  - BasicCataloguingRules
  :options: 
  - CatalogueBasicFormOptions
  :layout: 
  - CatalogueLayoutShow
  :filter:
    show_all: false
    show: true
